services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dropin
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  db:
  redis:
  minio:
